name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: bluesim

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
          zip -r bluesim.zip build/windows/
          mv bluesim.zip build/windows
      - name: deploy to server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
            DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
            ARGS: "-e -c -r"
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
            FOLDER: "build/windows"
            SERVER_IP: ${{ secrets.SERVER_IP }}
            USERNAME: ${{ secrets.USERNAME }}
            SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}/web/builds/windows/

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
          zip -r bluesim.zip build/linux/
          mv bluesim.zip build/linux
      - name: deploy to server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
            DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
            ARGS: "-e -c -r"
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
            FOLDER: "build/linux"
            SERVER_IP: ${{ secrets.SERVER_IP }}
            USERNAME: ${{ secrets.USERNAME }}
            SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}/web/builds/linux/

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --export "HTML5" build/web/index.html
      - name: deploy to server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
            DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
            ARGS: "-e -c -r"
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
            FOLDER: "build/web"
            SERVER_IP: ${{ secrets.SERVER_IP }}
            USERNAME: ${{ secrets.USERNAME }}
            SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}

  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot -v --export "Mac OSX" build/mac/$EXPORT_NAME.zip
      - name: deploy to server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
            DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
            ARGS: "-e -c -r"
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
            FOLDER: "build/mac"
            SERVER_IP: ${{ secrets.SERVER_IP }}
            USERNAME: ${{ secrets.USERNAME }}
            SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}/web/builds/mac/
