name: gd-test

on: [push, pull_request]

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@v2
    -
      name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    -
      name: Update tools
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/Scony/godot-gdscript-toolkit.git
    -
      name: Check style
      run: |
        gdformat $(find . -name '*.gd')
